export default [
    {
    "login": "AkhilSharma90",
    "id": 26513717,
    "node_id": "MDQ6VXNlcjI2NTEzNzE3",
    "avatar_url": "https://avatars.githubusercontent.com/u/26513717?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/AkhilSharma90",
    "html_url": "https://github.com/AkhilSharma90",
    "followers_url": "https://api.github.com/users/AkhilSharma90/followers",
    "following_url": "https://api.github.com/users/AkhilSharma90/following{/other_user}",
    "gists_url": "https://api.github.com/users/AkhilSharma90/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/AkhilSharma90/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/AkhilSharma90/subscriptions",
    "organizations_url": "https://api.github.com/users/AkhilSharma90/orgs",
    "repos_url": "https://api.github.com/users/AkhilSharma90/repos",
    "events_url": "https://api.github.com/users/AkhilSharma90/events{/privacy}",
    "received_events_url": "https://api.github.com/users/AkhilSharma90/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "john-smilga",
    "id": 42133389,
    "node_id": "MDQ6VXNlcjQyMTMzMzg5",
    "avatar_url": "https://avatars.githubusercontent.com/u/42133389?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/john-smilga",
    "html_url": "https://github.com/john-smilga",
    "followers_url": "https://api.github.com/users/john-smilga/followers",
    "following_url": "https://api.github.com/users/john-smilga/following{/other_user}",
    "gists_url": "https://api.github.com/users/john-smilga/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/john-smilga/subscriptions",
    "organizations_url": "https://api.github.com/users/john-smilga/orgs",
    "repos_url": "https://api.github.com/users/john-smilga/repos",
    "events_url": "https://api.github.com/users/john-smilga/events{/privacy}",
    "received_events_url": "https://api.github.com/users/john-smilga/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "amreshify",
    "id": 127320834,
    "node_id": "U_kgDOB5bDAg",
    "avatar_url": "https://avatars.githubusercontent.com/u/127320834?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/amreshify",
    "html_url": "https://github.com/amreshify",
    "followers_url": "https://api.github.com/users/amreshify/followers",
    "following_url": "https://api.github.com/users/amreshify/following{/other_user}",
    "gists_url": "https://api.github.com/users/amreshify/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/amreshify/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/amreshify/subscriptions",
    "organizations_url": "https://api.github.com/users/amreshify/orgs",
    "repos_url": "https://api.github.com/users/amreshify/repos",
    "events_url": "https://api.github.com/users/amreshify/events{/privacy}",
    "received_events_url": "https://api.github.com/users/amreshify/received_events",
    "type": "User",
    "site_admin": false
    }
    ]