export default [
    {
    "login": "monikapro",
    "id": 119788898,
    "node_id": "U_kgDOByPVYg",
    "avatar_url": "https://avatars.githubusercontent.com/u/119788898?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/monikapro",
    "html_url": "https://github.com/monikapro",
    "followers_url": "https://api.github.com/users/monikapro/followers",
    "following_url": "https://api.github.com/users/monikapro/following{/other_user}",
    "gists_url": "https://api.github.com/users/monikapro/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/monikapro/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/monikapro/subscriptions",
    "organizations_url": "https://api.github.com/users/monikapro/orgs",
    "repos_url": "https://api.github.com/users/monikapro/repos",
    "events_url": "https://api.github.com/users/monikapro/events{/privacy}",
    "received_events_url": "https://api.github.com/users/monikapro/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "amreshify",
    "id": 127320834,
    "node_id": "U_kgDOB5bDAg",
    "avatar_url": "https://avatars.githubusercontent.com/u/127320834?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/amreshify",
    "html_url": "https://github.com/amreshify",
    "followers_url": "https://api.github.com/users/amreshify/followers",
    "following_url": "https://api.github.com/users/amreshify/following{/other_user}",
    "gists_url": "https://api.github.com/users/amreshify/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/amreshify/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/amreshify/subscriptions",
    "organizations_url": "https://api.github.com/users/amreshify/orgs",
    "repos_url": "https://api.github.com/users/amreshify/repos",
    "events_url": "https://api.github.com/users/amreshify/events{/privacy}",
    "received_events_url": "https://api.github.com/users/amreshify/received_events",
    "type": "User",
    "site_admin": false
    }
    ]