export default {
    "login": "amreshpro",
    "id": 85226760,
    "node_id": "MDQ6VXNlcjg1MjI2NzYw",
    "avatar_url": "https://avatars.githubusercontent.com/u/85226760?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/amreshpro",
    "html_url": "https://github.com/amreshpro",
    "followers_url": "https://api.github.com/users/amreshpro/followers",
    "following_url": "https://api.github.com/users/amreshpro/following{/other_user}",
    "gists_url": "https://api.github.com/users/amreshpro/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/amreshpro/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/amreshpro/subscriptions",
    "organizations_url": "https://api.github.com/users/amreshpro/orgs",
    "repos_url": "https://api.github.com/users/amreshpro/repos",
    "events_url": "https://api.github.com/users/amreshpro/events{/privacy}",
    "received_events_url": "https://api.github.com/users/amreshpro/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Amresh Maurya",
    "company": "@amreshpro",
    "blog": "https://amreshpro.com",
    "location": "Rohtak,Haryana,India",
    "email": null,
    "hireable": null,
    "bio": "Web Developer | JavaScript | NodeJS |  React JS | C | C++\r\n\r\n",
    "twitter_username": "ursamresh",
    "public_repos": 20,
    "public_gists": 0,
    "followers": 2,
    "following": 3,
    "created_at": "2021-06-02T10:01:22Z",
    "updated_at": "2023-05-09T11:18:46Z"
    }